org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.daemon=false
android.useAndroidX=true
android.nonTransitiveRClass=true

# aarch64 主机：aapt2 与 AGP 自带的都是 x86_64 ELF，用 qemu 包装脚本代替。
# 注意 AGP 要求文件名必须是 aapt2。x64 主机请删除这一行。
android.aapt2FromMavenOverride=/home/tiny/sdks/aapt2-wrapper/aapt2
